# Generated by Django 4.0.4 on 2022-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_bonus_invitationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
